# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# send to fully-virtualized infrastructure: https://docs.travis-ci.com/user/reference/xenial/
sudo: required
dist: xenial

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  # default timeout is too low
  timeout: 600
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: true

language: java

stages:
  - name: compile
  - name: test
  - name: E2E
    if: type = cron
  - name: cleanup

jdk: "openjdk8"
jobs:
  include:
    # main profile
    - stage: compile
      jdk: openjdk8
      script: ./gradlew build -x test
    - stage: test
      jdk: openjdk8
      script: ./gradlew test
    - stage: test
      jdk: openjdk11
      script: ./gradlew test