# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


trigger:
  branches:
    include:
    - '*' 

variables:
  vmImage: 'ubuntu 16.04'
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle

jobs:
  - job: Build
    pool:
      vmImage: $(vmImage)
    steps:
      - task: Cache@2
        inputs:
          key: 'gradle | "$(Build.BuildId)"'
          restoreKeys: gradle
          path: $(GRADLE_USER_HOME)
        displayName: Gradle build cache
      - task: Gradle@2
        displayName: Compile
        inputs:
          gradleWrapperFile: 'gradlew'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          tasks: 'build -x test'
          options: '--info --stacktrace'

  - job: Test_Java8
    dependsOn: Build
    condition: succeeded()
    pool:
      vmImage: $(vmImage)
    steps:
      - task: Gradle@2
        displayName: Test @ Java 8
        inputs:
          gradleWrapperFile: 'gradlew'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          tasks: 'build'
          options: '--info --stacktrace'
  - job: Test_Java11
    dependsOn: Build
    condition: succeeded()
    pool:
      vmImage: $(vmImage)
    steps:
      - task: Gradle@2
        displayName: Test @ Java 8
        inputs:
          gradleWrapperFile: 'gradlew'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          tasks: 'build'
          options: '--info --stacktrace'
