plugins {
    id("java")
}

dependencies {
    implementation(project(":flink-core"))
    implementation(project(":flink-java"))
    implementation(project(":flink-scala"))
    implementation(project(":flink-runtime"))
    implementation(project(":flink-runtime-web"))
    implementation(project(":flink-optimizer"))
    implementation(project(":flink-clients"))
    implementation(project(":flink-streaming-java"))
    implementation(project(":flink-streaming-scala"))
    implementation(project(":flink-metrics:flink-metrics-core"))
    implementation(project(":flink-metrics:flink-metrics-jmx"))
    implementation(project(":flink-mesos"))
    implementation(project(":flink-container"))
    implementation(project(":flink-state-backends:flink-statebackend-rocksdb"))
    implementation(project(":flink-yarn"))
    implementation(project(":flink-filesystems:flink-hadoop-fs"))
    implementation(project(":flink-filesystems:flink-mapr-fs"))
//    implementation(project(":flink-scala-shell"))
    testImplementation(project(":flink-test-utils-parent:flink-test-utils-junit"))
    implementation(project(":flink-examples:flink-examples-batch"))
    implementation(project(":flink-examples:flink-examples-streaming"))
    implementation(project(":flink-examples:flink-examples-build-helper:flink-examples-streaming-state-machine"))
    implementation(project(":flink-examples:flink-examples-build-helper:flink-examples-streaming-click-event-count"))
    implementation(project(":flink-examples:flink-examples-build-helper:flink-examples-streaming-twitter"))
    implementation(project(":flink-libraries:flink-gelly-examples"))
    implementation(project(":flink-metrics:flink-metrics-dropwizard"))
    implementation(project(":flink-metrics:flink-metrics-graphite"))
    implementation(project(":flink-metrics:flink-metrics-influxdb"))
    implementation(project(":flink-metrics:flink-metrics-prometheus"))
    implementation(project(":flink-metrics:flink-metrics-statsd"))
    implementation(project(":flink-metrics:flink-metrics-datadog"))
    implementation(project(":flink-metrics:flink-metrics-slf4j"))
    implementation(project(":flink-libraries:flink-cep"))
    implementation(project(":flink-libraries:flink-cep-scala"))
    implementation(project(":flink-libraries:flink-gelly"))
    implementation(project(":flink-libraries:flink-gelly-scala"))
//    implementation(project(":flink-table:flink-table-uber"))
//    implementation(project(":flink-table:flink-table-uber-blink"))
//    implementation(project(":flink-table:flink-sql-client"))
    implementation(project(":flink-libraries:flink-state-processor-api"))
    implementation(project(":flink-filesystems:flink-azure-fs-hadoop"))
    implementation(project(":flink-filesystems:flink-s3-fs-hadoop"))
    implementation(project(":flink-filesystems:flink-s3-fs-presto"))
    implementation(project(":flink-filesystems:flink-swift-fs-hadoop"))
    implementation(project(":flink-filesystems:flink-oss-fs-hadoop"))
    implementation(project(":flink-queryable-state:flink-queryable-state-runtime"))
    implementation(project(":flink-python"))
    implementation(Libs.flink_shaded_netty_tcnative_dynamic)

    testImplementation(Libs.hamcrest_all)
}

description = "flink-dist"
