import org.gradle.api.Project
import org.gradle.kotlin.dsl.extra
import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrc// 
 *
 * Update this file with
 *   `$ ./gradlew buildSrc// `
 */
val Project.Libs
    get() = rootProject.extra.getOrPut("Libs") { LibNames(rootProject) }

class LibNames(val project: Project) {
    val scalaMinorVersion = project.scalaMinorVersion

    /**
     * https://github.com/sgroschupf/zkclient
     */
    val zkclient: String = "com.101tec:zkclient" // .zkclient
  
    /**
     * http://www.aliyun.com/product/oss
     */
    val aliyun_sdk_oss: String = "com.aliyun.oss:aliyun-sdk-oss" // .aliyun_sdk_oss
  
    /**
     * https://aws.amazon.com/sdkforjava
     */
    val aws_java_sdk_core: String = "com.amazonaws:aws-java-sdk-core" // 
        // .aws_java_sdk_core
  
    /**
     * https://aws.amazon.com/sdkforjava
     */
    val aws_java_sdk_dynamodb: String = "com.amazonaws:aws-java-sdk-dynamodb" // 
        // .aws_java_sdk_dynamodb
  
    /**
     * https://aws.amazon.com/sdkforjava
     */
    val aws_java_sdk_kms: String = "com.amazonaws:aws-java-sdk-kms" // .aws_java_sdk_kms
  
    /**
     * https://aws.amazon.com/sdkforjava
     */
    val aws_java_sdk_s3: String = "com.amazonaws:aws-java-sdk-s3" // .aws_java_sdk_s3
  
    /**
     * https://github.com/dataArtisans/frocksdb
     */
    val frocksdbjni: String = "com.data-artisans:frocksdbjni" // .frocksdbjni
  
    /**
     * https://github.com/datastax/java-driver
     */
    val cassandra_driver_core: String = "com.datastax.cassandra:cassandra-driver-core" // 
        // .com_datastax_cassandra
  
    /**
     * https://github.com/datastax/java-driver
     */
    val cassandra_driver_mapping: String = "com.datastax.cassandra:cassandra-driver-mapping" // 
        // .com_datastax_cassandra
  
    /**
     * https://github.com/EsotericSoftware/kryo
     */
    val kryo: String = "com.esotericsoftware.kryo:kryo" // .kryo
  
    /**
     * https://github.com/facebook/presto-hadoop-apache2
     */
    val hadoop_apache2: String = "com.facebook.presto.hadoop:hadoop-apache2" // 
        // .hadoop_apache2
  
    /**
     * https://github.com/facebook/presto
     */
    val presto_hive: String = "com.facebook.presto:presto-hive" // .presto_hive
  
    /**
     * https://github.com/oshi/oshi
     */
    val oshi_core: String = "com.github.oshi:oshi-core" // .oshi_core
  
    /**
     * https://github.com/scopt/scopt
     */
    val scopt: String = "com.github.scopt:scopt_${scalaMinorVersion}" // .scopt
  
    /**
     * http://wiremock.org
     */
    val wiremock: String = "com.github.tomakehurst:wiremock" // .wiremock
  
    /**
     * https://github.com/googleapis/google-cloud-java/tree/master/google-cloud-clients/google-cloud-pubsub
     */
    val google_cloud_pubsub: String = "com.google.cloud:google-cloud-pubsub" // 
        // .google_cloud_pubsub
  
    /**
     * http://findbugs.sourceforge.net/
     */
    val jsr305: String = "com.google.code.findbugs:jsr305" // .jsr305
  
    /**
     * https://github.com/google/guava
     */
    val guava: String = "com.google.guava:guava" // .guava
  
    /**
     * https://github.com/klarna/HiveRunner
     */
    val hiverunner: String = "com.klarna:hiverunner" // .hiverunner
  
    /**
     * http://unirest.io/
     */
    val unirest_java: String = "com.mashape.unirest:unirest-java" // .unirest_java
  
    /**
     * https://github.com/Azure/azure-sdk-for-java
     */
    val azure: String = "com.microsoft.azure:azure" // .azure
  
    /**
     * https://github.com/Netflix/Fenzo
     */
    val fenzo_core: String = "com.netflix.fenzo:fenzo-core" // .fenzo_core
  
    /**
     * https://www.rabbitmq.com
     */
    val amqp_client: String = "com.rabbitmq:amqp-client" // .amqp_client
  
    /**
     * https://github.com/spotify/docker-client
     */
    val docker_client: String = "com.spotify:docker-client" // .docker_client
  
    /**
     * https://github.com/square/okhttp
     */
    val okhttp: String = "com.squareup.okhttp3:okhttp" // .okhttp
  
    /**
     * https://github.com/twitter/chill
     */
    val chill: String = "com.twitter:chill_${scalaMinorVersion}" // .chill
  
    /**
     * http://github.com/twitter/hbc
     */
    val hbc_core: String = "com.twitter:hbc-core" // .hbc_core
  
    /**
     * https://akka.io/
     */
    val akka_actor: String = "com.typesafe.akka:akka-actor_${scalaMinorVersion}" // 
        // .com_typesafe_akka
  
    /**
     * https://akka.io/
     */
    val akka_protobuf: String = "com.typesafe.akka:akka-protobuf_${scalaMinorVersion}" // 
        // .com_typesafe_akka
  
    /**
     * https://akka.io/
     */
    val akka_remote: String = "com.typesafe.akka:akka-remote_${scalaMinorVersion}" // 
        // .com_typesafe_akka
  
    /**
     * https://akka.io/
     */
    val akka_slf4j: String = "com.typesafe.akka:akka-slf4j_${scalaMinorVersion}" // 
        // .com_typesafe_akka
  
    /**
     * https://akka.io/
     */
    val akka_stream: String = "com.typesafe.akka:akka-stream_${scalaMinorVersion}" // 
        // .com_typesafe_akka

    /**
     * https://akka.io/
     */
    val akka_testkit: String = "com.typesafe.akka:akka-testkit_${scalaMinorVersion}" // 
        // .com_typesafe_akka
  
    /**
     * http://commons.apache.org/proper/commons-cli/
     */
    val commons_cli: String = "commons-cli:commons-cli" // .commons_cli
  
    val commons_collections: String = "commons-collections:commons-collections" // 
        // .commons_collections
  
    /**
     * http://commons.apache.org/proper/commons-io/
     */
    val commons_io: String = "commons-io:commons-io" // .commons_io
  
    val de_fayard_buildsrcversions_gradle_plugin: String =
        "de.fayard.buildSrc// :de.fayard.buildSrc// .gradle.plugin" // 
        // .de_fayard_buildsrcversions_gradle_plugin
  
    /**
     * https://github.com/airlift/tpch
     */
    val tpch: String = "io.airlift.tpch:tpch" // .tpch
  
    /**
     * http://confluent.io
     */
    val kafka_schema_registry_client: String = "io.confluent:kafka-schema-registry-client" // 
        // .kafka_schema_registry_client
  
    /**
     * http://metrics.dropwizard.io
     */
    val metrics_core: String = "io.dropwizard.metrics:metrics-core" // 
        // .io_dropwizard_metrics
  
    /**
     * http://metrics.dropwizard.io
     */
    val metrics_graphite: String = "io.dropwizard.metrics:metrics-graphite" // 
        // .io_dropwizard_metrics
  
    /**
     * http://netty.io/
     */
    val netty: String = "io.netty:netty" // .netty
  
    /**
     * http://github.com/prometheus/client_java
     */
    val simpleclient: String = "io.prometheus:simpleclient" // .io_prometheus
  
    /**
     * http://github.com/prometheus/client_java
     */
    val simpleclient_httpserver: String = "io.prometheus:simpleclient_httpserver" // 
        // .io_prometheus
  
    /**
     * http://github.com/prometheus/client_java
     */
    val simpleclient_pushgateway: String = "io.prometheus:simpleclient_pushgateway" // 
        // .io_prometheus
  
    /**
     * http://fastutil.di.unimi.it/
     */
    val fastutil: String = "it.unimi.dsi:fastutil" // .fastutil
  
    /**
     * https://www.joda.org/joda-time/
     */
    val joda_time: String = "joda-time:joda-time" // .joda_time
  
    /**
     * http://junit.org
     */
    val junit: String = "junit:junit" // .junit
  
    /**
     * http://logging.apache.org/log4j/1.2/
     */
    val log4j: String = "log4j:log4j" // .log4j
  
    /**
     * https://github.com/irmen/Pyrolite
     */
    val pyrolite: String = "net.razorvine:pyrolite" // .pyrolite
  
    val py4j: String = "net.sf.py4j:py4j" // .py4j
  
    /**
     * http://avro.apache.org
     */
    val avro: String = "org.apache.avro:avro" // .avro
  
    /**
     * https://calcite.apache.org/avatica
     */
    val avatica_core: String = "org.apache.calcite.avatica:avatica-core" // 
        // .avatica_core
  
    /**
     * https://calcite.apache.org
     */
    val calcite_core: String = "org.apache.calcite:calcite-core" // .calcite_core
  
    /**
     * http://cassandra.apache.org
     */
    val cassandra_all: String = "org.apache.cassandra:cassandra-all" // .cassandra_all
  
    /**
     * https://commons.apache.org/proper/commons-compress/
     */
    val commons_compress: String = "org.apache.commons:commons-compress" // 
        // .commons_compress
  
    /**
     * http://commons.apache.org/proper/commons-lang/
     */
    val commons_lang3: String = "org.apache.commons:commons-lang3" // .commons_lang3
  
    /**
     * http://commons.apache.org/proper/commons-math/
     */
    val commons_math3: String = "org.apache.commons:commons-math3" // .commons_math3
  
    /**
     * http://curator.apache.org
     */
    val curator_recipes: String = "org.apache.curator:curator-recipes" // 
        // .org_apache_curator
  
    /**
     * http://curator.apache.org
     */
    val curator_test: String = "org.apache.curator:curator-test" // .org_apache_curator
  
    /**
     * http://db.apache.org/derby/
     */
    val derby: String = "org.apache.derby:derby" // .derby
  
    /**
     * http://flink.apache.org
     */
  
    val flink_shaded_asm_7: String = "org.apache.flink:flink-shaded-asm-7" // 
        // .flink_shaded_asm_7
  
    /**
     * http://flink.apache.org
     */
    val flink_shaded_guava: String = "org.apache.flink:flink-shaded-guava" // 
        // .flink_shaded_guava
  
    /**
     * http://flink.apache.org
     */
    val flink_shaded_hadoop_2: String = "org.apache.flink:flink-shaded-hadoop-2" // 
        // .flink_shaded_hadoop_2
  
    /**
     * http://flink.apache.org
     */
    val flink_shaded_jackson_module_jsonschema: String =
        "org.apache.flink:flink-shaded-jackson-module-jsonSchema" // 
        // .flink_shaded_jackson_module_jsonschema
  
    /**
     * http://flink.apache.org
     */
    val flink_shaded_jackson: String = "org.apache.flink:flink-shaded-jackson" // 
        // .flink_shaded_jackson
  
    /**
     * http://flink.apache.org
     */
    val flink_shaded_netty_tcnative_dynamic: String =
        "org.apache.flink:flink-shaded-netty-tcnative-dynamic" // 
        // .flink_shaded_netty_tcnative_dynamic
  
    /**
     * http://flink.apache.org
     */
    val flink_shaded_netty: String = "org.apache.flink:flink-shaded-netty" // 
        // .flink_shaded_netty
  
    val hadoop_aliyun: String = "org.apache.hadoop:hadoop-aliyun" // .hadoop_aliyun
  
    val hadoop_aws: String = "org.apache.hadoop:hadoop-aws" // .hadoop_aws
  
    val hadoop_azure: String = "org.apache.hadoop:hadoop-azure" // .hadoop_azure
  
    val hadoop_client: String = "org.apache.hadoop:hadoop-client" // .hadoop_client
  
    val hadoop_common: String = "org.apache.hadoop:hadoop-common" // .hadoop_common
  
    val hadoop_hdfs: String = "org.apache.hadoop:hadoop-hdfs" // .hadoop_hdfs
  
    val hadoop_mapreduce_client_core: String =
        "org.apache.hadoop:hadoop-mapreduce-client-core" // .hadoop_mapreduce_client_core
  
    val hadoop_minicluster: String = "org.apache.hadoop:hadoop-minicluster" // 
        // .hadoop_minicluster
  
    val hadoop_minikdc: String = "org.apache.hadoop:hadoop-minikdc" // .hadoop_minikdc
  
    val hadoop_openstack: String = "org.apache.hadoop:hadoop-openstack" // 
        // .hadoop_openstack
  
    val hadoop_yarn_api: String = "org.apache.hadoop:hadoop-yarn-api" // .hadoop_yarn_api
  
    val hadoop_yarn_client: String = "org.apache.hadoop:hadoop-yarn-client" // 
        // .hadoop_yarn_client
  
    /**
     * https://hbase.apache.org
     */
    val hbase_hadoop_compat: String = "org.apache.hbase:hbase-hadoop-compat" // 
        // .org_apache_hbase
  
    /**
     * https://hbase.apache.org
     */
    val hbase_hadoop2_compat: String = "org.apache.hbase:hbase-hadoop2-compat" // 
        // .org_apache_hbase
  
    /**
     * https://hbase.apache.org
     */
    val hbase_server: String = "org.apache.hbase:hbase-server" // .org_apache_hbase
  
      /**
       * https://hbase.apache.org
       */
      val hbase_client: String = "org.apache.hbase:hbase-client" // .org_apache_hbase
  
      /**
       * https://hbase.apache.org
       */
      val hbase_common: String = "org.apache.hbase:hbase-common" // .org_apache_hbase
  
    /**
     * http://maven.apache.org
     */
    val hcatalog_core: String = "org.apache.hive.hcatalog:hcatalog-core" // 
        // .hcatalog_core
  
    /**
     * http://hive.apache.org
     */
    val hive_hcatalog_core: String = "org.apache.hive.hcatalog:hive-hcatalog-core" // 
        // .hive_hcatalog_core
  
    /**
     * http://hive.apache.org
     */
    val hive_exec: String = "org.apache.hive:hive-exec" // .org_apache_hive
  
    /**
     * http://hive.apache.org
     */
    val hive_metastore: String = "org.apache.hive:hive-metastore" // .org_apache_hive
  
    /**
     * http://hive.apache.org
     */
    val hive_service: String = "org.apache.hive:hive-service" // .org_apache_hive
  
    /**
     * https://kafka.apache.org
     */
    val kafka_clients: String = "org.apache.kafka:kafka-clients" // .kafka_clients

    /**
     * https://kafka.apache.org
     */
    val kafka: String = "org.apache.kafka:kafka_${scalaMinorVersion}" // .kafka
  
    /**
     * https://logging.apache.org/log4j/2.x/
     */
    val log4j_core: String = "org.apache.logging.log4j:log4j-core" // .log4j_core
  
    /**
     * https://logging.apache.org/log4j/2.x/
     */
    val log4j_to_slf4j: String = "org.apache.logging.log4j:log4j-to-slf4j" // 
        // .log4j_to_slf4j
  
    /**
     * http://mesos.apache.org
     */
    val mesos: String = "org.apache.mesos:mesos" // .mesos
  
    val netlib_core: String = "com.github.fommil.netlib_core:core" // .netlib_core
  
    /**
     * http://nifi.apache.org
     */
    val nifi_site_to_site_client: String = "org.apache.nifi:nifi-site-to-site-client" // 
        // .nifi_site_to_site_client
  
    /**
     * http://orc.apache.org
     */
    val orc_core: String = "org.apache.orc:orc-core" // .orc_core
  
    /**
     * https://parquet.apache.org
     */
    val parquet_avro: String = "org.apache.parquet:parquet-avro" // .org_apache_parquet
  
    /**
     * https://parquet.apache.org
     */
    val parquet_hadoop: String = "org.apache.parquet:parquet-hadoop" // 
        // .org_apache_parquet
  
    /**
     * http://zookeeper.apache.org
     */
    val zookeeper: String = "org.apache.zookeeper:zookeeper" // .zookeeper
  
    /**
     * http://software.clapper.org/grizzled-slf4j/
     */
    val grizzled_slf4j: String = "org.clapper:grizzled-slf4j_${scalaMinorVersion}" // 
        // .grizzled_slf4j
  
    /**
     * http://janino-compiler.github.io/janino/
     */
    val janino: String = "org.codehaus.janino:janino" // .janino
  
    /**
     * https://github.com/elastic/elasticsearch
     */
    val elasticsearch_rest_high_level_client: String =
        "org.elasticsearch.client:elasticsearch-rest-high-level-client" // 
        // .org_elasticsearch_client
  
    /**
     * https://github.com/elastic/elasticsearch
     */
    val transport: String = "org.elasticsearch.client:transport" // 
        // .org_elasticsearch_client
  
    /**
     * https://github.com/elastic/elasticsearch
     */
    val transport_netty3_client: String = "org.elasticsearch.plugin:transport-netty3-client" // 
            // .org_elasticsearch_plugin
  
    /**
     * https://github.com/elastic/elasticsearch
     */
    val transport_netty4_client: String = "org.elasticsearch.plugin:transport-netty4-client" // 
        // .org_elasticsearch_plugin
  
    /**
     * https://github.com/elastic/elasticsearch
     */
    val elasticsearch: String = "org.elasticsearch:elasticsearch" // .elasticsearch
  
    /**
     * https://github.com/hamcrest/JavaHamcrest
     */
    val hamcrest_all: String = "org.hamcrest:hamcrest-all" // .hamcrest_all
  
    /**
     * http://www.influxdb.org
     */
    val influxdb_java: String = "org.influxdb:influxdb-java" // .influxdb_java
  
    /**
     * http://www.javassist.org/
     */
    val javassist: String = "org.javassist:javassist" // .javassist
  
    val jcip_annotations: String = "net.jcip:jcip-annotations" // .jcip_annotations
  
    val jline_reader: String = "org.jline:jline-reader" // .org_jline
  
    val jline_terminal: String = "org.jline:jline-terminal" // .org_jline
  
    /**
     * https://www.joda.org/${joda.artifactId}/
     */
    val joda_convert: String = "org.joda:joda-convert" // .joda_convert
  
    /**
     * https://jsoup.org/
     */
    val jsoup: String = "org.jsoup:jsoup" // .jsoup
  
    /**
     * https://github.com/lz4/lz4-java
     */
    val lz4_java: String = "org.lz4:lz4-java" // .lz4_java
  
    /**
     * https://github.com/mockito/mockito
     */
    val mockito_core: String = "org.mockito:mockito-core" // .mockito_core
  
    /**
     * http://www.powermock.org
     */
    val powermock_api_mockito2: String = "org.powermock:powermock-api-mockito2" // 
        // .org_powermock
  
    /**
     * http://www.powermock.org
     */
    val powermock_module_junit4: String = "org.powermock:powermock-module-junit4" // 
        // .org_powermock
  
    /**
     * https://projectlombok.org
     */
    val lombok: String = "org.projectlombok:lombok" // .lombok
  
    /**
     * http://github.com/ronmamo/reflections
     */
    val reflections: String = "org.reflections:reflections" // .reflections
  
    /**
     * https://www.scala-lang.org/
     */
    val scala_compiler: String = "org.scala-lang:scala-compiler" // .org_scala_lang
  
    /**
     * https://www.scala-lang.org/
     */
    val scala_library: String = "org.scala-lang:scala-library" // .org_scala_lang
  
    val scala_r: String = "org.scala-lang:scala-r" // .org_scala_lang
  
    val scala_parser_combinators: String = "org.scala-lang.modules:scala-parser-combinators_${scalaMinorVersion}" // .scala_parser_combinators
  
    /**
     * https://www.scala-lang.org/
     */
    val scala_reflect: String = "org.scala-lang:scala-reflect" // .org_scala_lang
  
    /**
     * http://www.scalatest.org
     */
    val scalatest: String = "org.scalatest:scalatest_${scalaMinorVersion}" // .org_scalatest
  
    /**
     * http://moepii.sourceforge.net/
     */
    val irclib: String = "org.schwering:irclib" // .irclib
  
    /**
     * http://www.slf4j.org
     */
    val slf4j_api: String = "org.slf4j:slf4j-api" // .org_slf4j
  
    /**
     * http://www.slf4j.org
     */
    val slf4j_log4j12: String = "org.slf4j:slf4j-log4j12" // .org_slf4j
  
    /**
     * https://github.com/xerial/snappy-java
     */
    val snappy_java: String = "org.xerial.snappy:snappy-java" // .snappy_java
  }
